{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.4.0-alpha05.aar",
          "url": "camera-view-1.4.0-alpha05.aar",
          "size": 94427,
          "sha512": "98ac97da1233f187bed2a2e16886b04e1ee0840c82f34f8ef3f43a6ffb73bb5adbf6e7c66378f32b7f24ae85f15b13f812ec301397d0c3d3d955f36388f8da80",
          "sha256": "a14488aaf4a3b07d347acc2ef4813ed3a54589e51203c6adf72d309d8ee10126",
          "sha1": "43400638a65997a2c52dd2ecd2044cf96354a7da",
          "md5": "50c4c30cd108477a0b1f1e53948977f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.4.0-alpha05.aar",
          "url": "camera-view-1.4.0-alpha05.aar",
          "size": 94427,
          "sha512": "98ac97da1233f187bed2a2e16886b04e1ee0840c82f34f8ef3f43a6ffb73bb5adbf6e7c66378f32b7f24ae85f15b13f812ec301397d0c3d3d955f36388f8da80",
          "sha256": "a14488aaf4a3b07d347acc2ef4813ed3a54589e51203c6adf72d309d8ee10126",
          "sha1": "43400638a65997a2c52dd2ecd2044cf96354a7da",
          "md5": "50c4c30cd108477a0b1f1e53948977f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-view-1.4.0-alpha05-sources.jar",
          "url": "camera-view-1.4.0-alpha05-sources.jar",
          "size": 81469,
          "sha512": "2c1b774c92577b709d0c23474b31f55c8586866ee6b01294c787bf9049ab97f6d232ac1ae59277d80a52e565f560f2d0c6dc263cdcf9ca76df6bcbda74272f28",
          "sha256": "32d9fe2b8ebb77c5edfbce125d415d4881886da14be374d73d1933a36f11ef80",
          "sha1": "138ee0e91161f586ae8c40c93ddc64d5da3161cd",
          "md5": "01120a070ee726dbd5af038e8e8876a4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-view-1.4.0-alpha05-versionMetadata.json",
          "url": "camera-view-1.4.0-alpha05-versionMetadata.json",
          "size": 14384,
          "sha512": "b3af6cc0297bb86eaad9a1a43eba2cb80223fbcc09d6b5b988ecd62ecde896b283e1f395bbbb77abb116ec9f44305260f48adadb5f6a9c077a259698e3dd79fe",
          "sha256": "c7c555d7339f2c7dcab188abab80914d08315929aad62dc9bc44e0e305742ceb",
          "sha1": "69eabd1da9ac62df7d664659394119a5025969ce",
          "md5": "5d51fc99abf3faae7737c6cdf301b22a"
        }
      ]
    }
  ]
}