{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-effects",
    "version": "1.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "camera-effects-1.4.0-alpha05.aar",
          "url": "camera-effects-1.4.0-alpha05.aar",
          "size": 36280,
          "sha512": "ecabaea9181519294f0663c0b0bdfcd74d45dcc3606fc55b84d6d47fd644accb370224f942225e4ec6c0fe0caa9c3fc8ecc7e0334274d12d22097ab0cbe6d9e1",
          "sha256": "19f147861cb17b827d065d6b030d74ddf97d7e70c4e445322635c2e0e2770e92",
          "sha1": "e5b315bf903e3a2e7db2c3dd7dcd3320fc9f34df",
          "md5": "58fdf837dee1b5d654edea0946fbc33c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-effects-1.4.0-alpha05.aar",
          "url": "camera-effects-1.4.0-alpha05.aar",
          "size": 36280,
          "sha512": "ecabaea9181519294f0663c0b0bdfcd74d45dcc3606fc55b84d6d47fd644accb370224f942225e4ec6c0fe0caa9c3fc8ecc7e0334274d12d22097ab0cbe6d9e1",
          "sha256": "19f147861cb17b827d065d6b030d74ddf97d7e70c4e445322635c2e0e2770e92",
          "sha1": "e5b315bf903e3a2e7db2c3dd7dcd3320fc9f34df",
          "md5": "58fdf837dee1b5d654edea0946fbc33c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-effects-1.4.0-alpha05-sources.jar",
          "url": "camera-effects-1.4.0-alpha05-sources.jar",
          "size": 31868,
          "sha512": "77430ca79ffae75f548976bd7245bf350121a98e1b678043535fae3fc4d43c86d50f97e290caa835d7a0ce5da0843a673f90279c79a65e3f7edd4b29a39c3335",
          "sha256": "dfa884db1e7ffdd9a47a1683971271055a2348ecf284c3f782b8854f068757b7",
          "sha1": "5b295cdd537770437d493863485e4cde74a3272f",
          "md5": "d021bcc4bccaa75920de919b35aa3237"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-effects-1.4.0-alpha05-versionMetadata.json",
          "url": "camera-effects-1.4.0-alpha05-versionMetadata.json",
          "size": 1424,
          "sha512": "b8dc192585cc0dab85a334a9a493e249cdc5f68411af1fa0ab2601a401b9af3aca5bd81f629e07ee9591b311e9f05355a43d0ee0c9542e1c724dae23c7ad41ce",
          "sha256": "34cce3fe191d1db53854c61b1a4bd8dff807d346dc547ee1c5be7e946a016ee4",
          "sha1": "83f4bb45ae29dd2d2926224813cce36ad738c2fd",
          "md5": "ce7ab9c2640ec21f0d553a4e0d5e7dd5"
        }
      ]
    }
  ]
}