{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-viewfinder-compose",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "url": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "size": 2158,
          "sha512": "97daff29290e78b4b56a098ca257a76c33428391e932b86be43c3be77df97945fa93905165e859e3ebc03c5f9a0f325a959adef4478590c6de1b489d6ebcdc35",
          "sha256": "59b8901727b18bc9ff769621188968077f2495d275f5af7cf22e28eacf963a68",
          "sha1": "793a9f545bfb5ffd1bea9d12d5b9fd4f7c858ad7",
          "md5": "08b7861dd195524439d20ddbef50e407"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "url": "camera-viewfinder-compose-1.0.0-alpha01.aar",
          "size": 2158,
          "sha512": "97daff29290e78b4b56a098ca257a76c33428391e932b86be43c3be77df97945fa93905165e859e3ebc03c5f9a0f325a959adef4478590c6de1b489d6ebcdc35",
          "sha256": "59b8901727b18bc9ff769621188968077f2495d275f5af7cf22e28eacf963a68",
          "sha1": "793a9f545bfb5ffd1bea9d12d5b9fd4f7c858ad7",
          "md5": "08b7861dd195524439d20ddbef50e407"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01-sources.jar",
          "url": "camera-viewfinder-compose-1.0.0-alpha01-sources.jar",
          "size": 794,
          "sha512": "32e6df4225773993e3931f18b5eb7f36f0cf7b8aec7e6d5aeccf83a555b1b0cdae804c7d028c4552d1a556dc443c386e2a86fb7b1f7dca386a0041fdad7571fc",
          "sha256": "da96d36f014fcf2d840e20d4de146f859a4a8ded0230213db0584b6133f95ea1",
          "sha1": "32a09383fe811d118cbd08b1bc63c0cfed8fe9cd",
          "md5": "fc7975875597ff2669314297d82aad6b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-viewfinder-compose-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-viewfinder-compose-1.0.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}