{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-alpha05.aar",
          "url": "camera-camera2-1.4.0-alpha05.aar",
          "size": 464647,
          "sha512": "55d565bed53b93941733fb146301af68ce3b027afbefa5fe2af2d5721004c78d2b9d9e529d426a8f47631541e4387f1aad28c4a87092660d8b0d2344b3984cf9",
          "sha256": "91067c70a062d5046a253ea222dfc0e889656ca6f4d2a3d4bfb7da0889a7920e",
          "sha1": "f3bfe608892ca94aa8b0891a57448c584343913b",
          "md5": "e1663b07ef9cd8a0f7e3bce8256ca6bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-alpha05.aar",
          "url": "camera-camera2-1.4.0-alpha05.aar",
          "size": 464647,
          "sha512": "55d565bed53b93941733fb146301af68ce3b027afbefa5fe2af2d5721004c78d2b9d9e529d426a8f47631541e4387f1aad28c4a87092660d8b0d2344b3984cf9",
          "sha256": "91067c70a062d5046a253ea222dfc0e889656ca6f4d2a3d4bfb7da0889a7920e",
          "sha1": "f3bfe608892ca94aa8b0891a57448c584343913b",
          "md5": "e1663b07ef9cd8a0f7e3bce8256ca6bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-1.4.0-alpha05-sources.jar",
          "url": "camera-camera2-1.4.0-alpha05-sources.jar",
          "size": 361540,
          "sha512": "4f1ae2b84f528ee9127bbb51983731c0dd7d53d2768c6be5d9b316bf33b67f9bd51ddbfe6b4724628c485964dfca16cfa8e1f5be897500b4d45f080e114edbd5",
          "sha256": "c76c0d19d279bf390b47c1d2e7bcba6b966a5ca04f2c10884ea8b6801a333311",
          "sha1": "41b9ed0aaf1357e0c5887f5b82b19bde052a3d2b",
          "md5": "1b27316c70d0f5893b3ccf0eec9dc9c3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-camera2-1.4.0-alpha05-versionMetadata.json",
          "url": "camera-camera2-1.4.0-alpha05-versionMetadata.json",
          "size": 3277,
          "sha512": "3457aaf1daae3c23df1afa125444b2c9febccd6c8eee62fddb37b74e4d217ea8183aafd55fe757191cd7be2d45e078616d54dbb1f172558a02fe063cbec75f1f",
          "sha256": "d8cec82581880afa10cba43907db64357c3f6a765fd7598a042eb7943b1019f4",
          "sha1": "f1e5deb7118484ad497eec922b64b108f5993b67",
          "md5": "6d6e3a9187e23ee6c4cd6dfcaa04b2b9"
        }
      ]
    }
  ]
}