{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-integration",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 845481,
          "sha512": "2936bef5dff53ad654426e9fdf25caab1e74316f6b2895de444cce14c250e243c67d7842ff1c72c41b37a01b843d44a1272037db8cfa7d4c2771a206a4c996ef",
          "sha256": "329282c70a8c6c39414a818eb5377f8b97dfc8b4ec306326e9eddfe643a15358",
          "sha1": "3897c70e561de1576c8d7dc4ec23ae04861da92f",
          "md5": "ebaa89470299302c53060eeb2f8c50b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-listenablefuture-callback",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 845481,
          "sha512": "2936bef5dff53ad654426e9fdf25caab1e74316f6b2895de444cce14c250e243c67d7842ff1c72c41b37a01b843d44a1272037db8cfa7d4c2771a206a4c996ef",
          "sha256": "329282c70a8c6c39414a818eb5377f8b97dfc8b4ec306326e9eddfe643a15358",
          "sha1": "3897c70e561de1576c8d7dc4ec23ae04861da92f",
          "md5": "ebaa89470299302c53060eeb2f8c50b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "size": 263654,
          "sha512": "9258d49ac40adeb79780dab5acae684b0aa7505765ec5b08619bda7b9c93cf7e035bfdab0a0db292db6918202303b5bb2b5b927e349cd86c1fc17fc025051c36",
          "sha256": "503bb63bb3ed8c14d290d0f24e9d8ad1e7546c8ad75e985064b4d7c6ffb18835",
          "sha1": "3b91b33690c57b0c23841a1a3e428ddf12aee97d",
          "md5": "e5e4247b0ea4cda249fa4409cbd32f87"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "size": 4017,
          "sha512": "efd9809e75691f3ad946b1adc1369b1cfeb3d2f976e7a813bc26df8216745a18a4341792c27280bf08c51fa0443f651ffd8a5c36829e579462ca6a0e96391e48",
          "sha256": "cf64f3ef620f0dd2254bc60c6fac846012d25fd518b3a8253029712ace321a3c",
          "sha1": "8fa26dc17e7d5dafff21916b28a69e2597fa654f",
          "md5": "7b1a3f19da1f03bb292b1980f447e23b"
        }
      ]
    }
  ]
}