{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-mlkit-vision",
    "version": "1.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-interfaces",
          "version": {
            "requires": "16.0.0",
            "prefers": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-mlkit-vision-1.4.0-alpha05.aar",
          "url": "camera-mlkit-vision-1.4.0-alpha05.aar",
          "size": 7917,
          "sha512": "4b97204f42672741fb5cbeae0008455ddb7789ce8d87a58395be1fdd193decf14939adf5ee3a8013295d960c38e0d0bd4c1432d40686e10d12305da746bc03af",
          "sha256": "ed6f725a85a918b9fb25474d7f978f8e115b9de61753418e75eecc243847597f",
          "sha1": "383055edd8d23ebf8342c35896e76c7056b09f59",
          "md5": "8a221a2d93f52579c06a634a5230a005"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-alpha05"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-interfaces",
          "version": {
            "requires": "16.0.0",
            "prefers": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-mlkit-vision-1.4.0-alpha05.aar",
          "url": "camera-mlkit-vision-1.4.0-alpha05.aar",
          "size": 7917,
          "sha512": "4b97204f42672741fb5cbeae0008455ddb7789ce8d87a58395be1fdd193decf14939adf5ee3a8013295d960c38e0d0bd4c1432d40686e10d12305da746bc03af",
          "sha256": "ed6f725a85a918b9fb25474d7f978f8e115b9de61753418e75eecc243847597f",
          "sha1": "383055edd8d23ebf8342c35896e76c7056b09f59",
          "md5": "8a221a2d93f52579c06a634a5230a005"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-mlkit-vision-1.4.0-alpha05-sources.jar",
          "url": "camera-mlkit-vision-1.4.0-alpha05-sources.jar",
          "size": 5562,
          "sha512": "2f9c14d8a034ce288f225a0c39068d2723a158a86767cdf870b6d2e7a91905044a4a4518acdd9af7cf3e70dd6e1ab15f7b37999551381a618165264bdf73f1ca",
          "sha256": "012caccc183a4ffd458563e25d18a81e6031d5410c3ffd8767f0ed7c27fcbdad",
          "sha1": "71f3e64e667c180da000730e55765f4e9277fd89",
          "md5": "85960e8d9b2a209981c9ae82607556dd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-mlkit-vision-1.4.0-alpha05-versionMetadata.json",
          "url": "camera-mlkit-vision-1.4.0-alpha05-versionMetadata.json",
          "size": 1182,
          "sha512": "58e5af44d70886b77d5503d645caa6a0453e2e196f2480d82684c5af82535536db50c09a0e50d399640bf7d688deb6411cd8bd68e8adfb451922c8c46af8083b",
          "sha256": "65b5709f3e6ed237bb46a2d457db40597931dafb2e80fa3ac1fbe0ebbff08f31",
          "sha1": "b089cdd921f3d736975d60a5226506755537282d",
          "md5": "1e8bd038e0fbdec30edba84a46c3abbe"
        }
      ]
    }
  ]
}